### ISSUE TITLE
package failed to install, exited with error code: 128

### ISSUE THREAD

**Issue by csiddabattula** [yxliang01/eth-mine-when-need#1]
Package failed with error code: 128

87 silly pacote range manifest for xmlhttprequest@* fetched in 373ms
88 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
89 verbose stack Error: exited with error code: 128
89 verbose stack     at ChildProcess.onexit (C:\Users\myandmyself\AppData\Roaming\npm\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
89 verbose stack     at emitTwo (events.js:106:13)
89 verbose stack     at ChildProcess.emit (events.js:191:7)
89 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by yxliang01** [comment]
Thanks for repotting. May I have the full log? So that, I can gain a better understanding of the problem. So far, it seems to be a problem of a dependency.

Thanks!

**Comment by csiddabattula** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli
'C:\\Users\\euser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'eth-mine-when-need' ]
2 info using npm@5.0.3
3 info using node@v7.4.0
4 verbose npm-session 06d5f36a699a3184
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 http://registry.npmjs.org/eth-mine-when-need 5919ms
(from cache)
8 silly pacote tag manifest for eth-mine-when-need@latest fetched in 5972ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule eth-mine-when-need@1.1.6 checking installable
status
14 http fetch GET 304 http://registry.npmjs.org/babel-runtime 319ms (from
cache)
15 silly pacote range manifest for babel-runtime@^6.23.0 fetched in 327ms
16 silly resolveWithNewModule babel-runtime@6.23.0 checking installable
status
17 http fetch GET 304 http://registry.npmjs.org/assert 505ms (from cache)
18 http fetch GET 304 http://registry.npmjs.org/defined 506ms (from cache)
19 silly pacote range manifest for assert@^1.4.1 fetched in 513ms
20 silly resolveWithNewModule assert@1.4.1 checking installable status
21 http fetch GET 304 http://registry.npmjs.org/colors 511ms (from cache)
22 silly pacote range manifest for defined@^1.0.0 fetched in 511ms
23 silly resolveWithNewModule defined@1.0.0 checking installable status
24 http fetch GET 304 http://registry.npmjs.org/chalk 515ms (from cache)
25 http fetch GET 304 http://registry.npmjs.org/figlet 511ms (from cache)
26 silly pacote range manifest for colors@^1.1.2 fetched in 518ms
27 silly resolveWithNewModule colors@1.1.2 checking installable status
28 http fetch GET 304 http://registry.npmjs.org/web3 511ms (from cache)
29 silly pacote range manifest for chalk@^1.1.3 fetched in 525ms
30 silly resolveWithNewModule chalk@1.1.3 checking installable status
31 silly pacote range manifest for figlet@^1.2.0 fetched in 523ms
32 silly resolveWithNewModule figlet@1.2.0 checking installable status
33 silly pacote range manifest for web3@^0.18.2 fetched in 526ms
34 silly resolveWithNewModule web3@0.18.4 checking installable status
35 http fetch GET 304 http://registry.npmjs.org/ethereum-go-ipc 907ms (from
cache)
36 silly pacote range manifest for ethereum-go-ipc@^0.1.5 fetched in 909ms
37 silly resolveWithNewModule ethereum-go-ipc@0.1.5 checking installable
status
38 http fetch GET 304 http://registry.npmjs.org/es6-promisify 3436ms (from
cache)
39 silly pacote range manifest for es6-promisify@^5.0.0 fetched in 3449ms
40 silly resolveWithNewModule es6-promisify@5.0.0 checking installable
status
41 http fetch GET 304 http://registry.npmjs.org/util 422ms (from cache)
42 silly pacote version manifest for util@0.10.3 fetched in 428ms
43 silly resolveWithNewModule util@0.10.3 checking installable status
44 http fetch GET 304 http://registry.npmjs.org/inherits 386ms (from cache)
45 silly pacote version manifest for inherits@2.0.1 fetched in 389ms
46 silly resolveWithNewModule inherits@2.0.1 checking installable status
47 http fetch GET 304 http://registry.npmjs.org/core-js 497ms (from cache)
48 silly pacote range manifest for core-js@^2.4.0 fetched in 524ms
49 silly resolveWithNewModule core-js@2.4.1 checking installable status
50 http fetch GET 304 http://registry.npmjs.org/regenerator-runtime 537ms
(from cache)
51 silly pacote range manifest for regenerator-runtime@^0.10.0 fetched in
538ms
52 silly resolveWithNewModule regenerator-runtime@0.10.5 checking
installable status
53 http fetch GET 304 http://registry.npmjs.org/ansi-styles 437ms (from
cache)
54 http fetch GET 304 http://registry.npmjs.org/supports-color 445ms (from
cache)
55 silly pacote range manifest for ansi-styles@^2.2.1 fetched in 458ms
56 silly resolveWithNewModule ansi-styles@2.2.1 checking installable status
57 silly pacote range manifest for supports-color@^2.0.0 fetched in 457ms
58 silly resolveWithNewModule supports-color@2.0.0 checking installable
status
59 http fetch GET 304 http://registry.npmjs.org/has-ansi 858ms (from cache)
60 http fetch GET 304 http://registry.npmjs.org/strip-ansi 859ms (from
cache)
61 silly pacote range manifest for has-ansi@^2.0.0 fetched in 862ms
62 silly resolveWithNewModule has-ansi@2.0.0 checking installable status
63 http fetch GET 304 http://registry.npmjs.org/escape-string-regexp 863ms
(from cache)
64 silly pacote range manifest for strip-ansi@^3.0.0 fetched in 866ms
65 silly resolveWithNewModule strip-ansi@3.0.1 checking installable status
66 silly pacote range manifest for escape-string-regexp@^1.0.2 fetched in
870ms
67 silly resolveWithNewModule escape-string-regexp@1.0.5 checking
installable status
68 http fetch GET 304 http://registry.npmjs.org/ansi-regex 300ms (from
cache)
69 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 304ms
70 silly resolveWithNewModule ansi-regex@2.1.1 checking installable status
71 http fetch GET 304 http://registry.npmjs.org/es6-promise 755ms (from
cache)
72 silly pacote range manifest for es6-promise@^4.0.3 fetched in 761ms
73 silly resolveWithNewModule es6-promise@4.1.0 checking installable status
74 silly pacote range manifest for web3@^0.15.3 fetched in 26ms
75 silly resolveWithNewModule web3@0.15.3 checking installable status
76 http fetch GET 304 http://registry.npmjs.org/bluebird 344ms (from cache)
77 silly pacote range manifest for bluebird@^3.3.5 fetched in 353ms
78 silly resolveWithNewModule bluebird@3.5.0 checking installable status
79 http fetch GET 304 http://registry.npmjs.org/utf8 223ms (from cache)
80 silly pacote range manifest for utf8@^2.1.1 fetched in 233ms
81 silly resolveWithNewModule utf8@2.1.2 checking installable status
82 http fetch GET 304 http://registry.npmjs.org/xmlhttprequest 236ms (from
cache)
83 http fetch GET 304 http://registry.npmjs.org/crypto-js 237ms (from cache)
84 silly pacote range manifest for xmlhttprequest@* fetched in 239ms
85 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable
status
86 silly pacote range manifest for crypto-js@^3.1.4 fetched in 241ms
87 silly resolveWithNewModule crypto-js@3.1.8 checking installable status
88 silly fetchPackageMetaData error for bignumber.js@git+
https://github.com/debris/bignumber.js.git#master exited with error code:
128
89 verbose stack Error: exited with error code: 128
89 verbose stack     at ChildProcess.onexit
(C:\Users\euser\AppData\Roaming\npm\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
89 verbose stack     at emitTwo (events.js:106:13)
89 verbose stack     at ChildProcess.emit (events.js:191:7)
89 verbose stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:215:12)
90 verbose cwd C:\Users\euser
91 verbose Windows_NT 6.3.9600
92 verbose argv "C:\\Program Files\\nodejs\\node.exe"
"C:\\Users\\euser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js"
"install" "-g" "eth-mine-when-need"
93 verbose node v7.4.0
94 verbose npm  v5.0.3
95 error exited with error code: 128
96 verbose exit [ 1, true ]

**Comment by yxliang01** [comment]
@csiddabattula Have you tried:
1. Retrying the installation process
2. Use browser access https://github.com/debris/bignumber.js.git#master to see whether it's accessible
3. Update node to version 8

I have seen lots of reports like https://github.com/npm/npm/issues/16830 . However, I couldn't reproduce this error using node 8.1.2, npm 5.0.3, mac os

If you have further information that can provide, please let me know.
Thanks!

**Comment by yxliang01** [comment]
Closed due to no further feedback from the user for 9 months. @csiddabattula Please feel free to reopen this issue and comment more if you still have this problem. If would also be great to inform us if you managed to solve this issue and share what you have done.

Thanks
