### ISSUE TITLE
Use in other javascript script as a library

### ISSUE THREAD

**Issue by vinodrajendran001** [yxliang01/eth-mine-when-need#2]
Hi,

May I know how to call "eth-mine-when-need" command from the javascript?

Thanks,
Vinod

**Comment by yxliang01** [comment]
Hello Vinod,

You can just `require("eth-mine-when-need")` or `import emwn from 'eth-mine-when-need'` (if using ES2015 or above or typescript). Then you can create a new `mine_when_need` object. May I know whether you are encountering any problem when importing the library?

Thanks

**Comment by yxliang01** [comment]
@vinodrajendran001 Would be great if you can comment here if you have already solved this. Will close this issue if no further response in 7 days.

Thanks

**Comment by vinodrajendran001** [comment]
Unfortunately, at the moment I didn't use ES2015 or above. Will try this solution after migrating the project into latest JavaScript framework.

**Comment by yxliang01** [comment]
@vinodrajendran001 Then you can use `require("eth-mine-when-need")` this won't require your project to use ES2015 or above.
